---
title: "Road Accident"
author: "Agasiya"
date: "12/7/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, comment = NA)

library(tidyverse)
library(gtsummary)
library(magrittr)
library(readxl)
zhib <- read_rds('zhib.rds')
View(zhib)
```


```{r}
zhib %>% select(1:10) %>% drop_na() %>%
  group_by(Year) %>% 
   summarise(
     mean_crush = mean(All_Crashes),
     mean_casualty = mean(All_casualties),
     mean_fata = mean(Fatalities)
   ) %>% 
  ggplot(aes(x = Year)) +
    geom_line(aes(y = mean_crush, color = "cyan")) + 
    geom_line(aes(y = mean_casualty, color = "red")) +
    geom_line(aes(y = mean_fata, color = "blue"))
```



```{r}
#reg <- zhib %>% select(1:10) %>% drop_na()
lm(data = zhib, All_crashes ~ Fatalities, family = poisson)
```
```{r}
zhib %>% select(1:10) %>% drop_na() %>% group_by(Year) %>% summarise(
  crashes = mean(All_Crashes), 
  All_casualties, Fatalities, Estimated_Population_ht, Registered_Vehicles
) %>% 
  ggplot(aes(x = as.factor(Year))) +
  geom_line(aes(y = crashes))
```



```{r}
ggplot(data = zhib) + geom_boxplot(aes(x = as.factor(Year), y = Fatalities, fill = "red"))
```

